export default {
  Художники: {
    1: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    2: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    3: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    4: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    5: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    6: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    7: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    8: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    9: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    10: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    11: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    12: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
  },
  Картины: {
    1: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    2: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    3: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    4: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    5: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    6: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    7: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    8: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    9: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    10: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    11: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
    12: {
      categoryAnswers: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      isEnd: false,
    },
  },
};
